server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 5000

spring:
  spring:
    profiles:
      active: native
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/
      database: produto
      auto-index-creation: true

application-version: 2.0